### PR TITLE
Fix getVelocityAffectingPos Mixin Conflicts + Issues Below Y=0

### PR DESCRIPTION
**Pull request by sleepingdragoninn**
- Uses `Math.floor()` to prevent rounding errors below y=0, causing all velocity-affecting blocks to stop working.
- Conditions the alternate logic on the relevant block being _specifically_ from CPlus - using simple extensions and `instanceof`.

### CODE REVIEW

**Review by Siuolplex — CHANGES_REQUESTED** [review]
Aye this is pretty good, just make sure to also change the slab as that was the whole initial reason behind this mixin existing

**Comment by Siuolplex** [comment]
In fact you should just be able to check if the block you are in is a slab from C+, as the whole walls, gates, and fences thing (is supposed to) reverts to the vanilla behavior. I'll check when I wake up more

**Comment by Siuolplex** [comment]
Alright so it shouldnt be an issue if we just check for a Slab/Stairs Block in the player's current position. Which was what I originally meant it to do.

**Comment by sisby-folk** [comment]
Like this? @Siuolplex

**Comment by sisby-folk** [comment]
Revised now.

**Pull request merged**
