### PR TITLE
Tinted glass blocks.

### PR DESCRIPTION
**Pull request by Ibex80**
No lang, no recipes and purple boi model doesn't work.

### CODE REVIEW

**Comment by Siuolthepic** [comment]
If you can finish the lang, recipe, and model, Ill get it in.

**Comment by wafflecoffee** [comment]
I'm working on recipes and lang right now, and the purple one works fine

**Comment by wafflecoffee** [comment]
@Ibex80 For some reason I can't seem to be able to push to your branch, but I've created a new branch on this repo, mind if I just merge that?

**Comment by Ibex80** [comment]
Sure

**Comment by Ibex80** [comment]
@wafflecoffee I also gave you access to push to my fork

**Comment by wafflecoffee** [comment]
It's not the access that's an issue, it's trying to tell me it's a non-ff when it is

**Pull request closed without merging**
