### PR TITLE
Optimize assets.

### PR DESCRIPTION
**Pull request by RDKRACZ**
Lossless - I used optipng (`optipng -o7 -strip all *.png`).

_I'm gonna update this pl_pl.json somewhere in the future... for sure_

### CODE REVIEW

**Comment by Cart3r1234** [comment]
Awesome.  I don't see any reasons not to merge, but I'm going to check with the others first.

**Comment by wafflecoffee** [comment]
looks fine to me, mind if I run oxipng on top as well (to shave off another few bytes)?

**Comment by RDKRACZ** [comment]
> mind if I run oxipng on top as well (to shave off another few bytes)?

Tried now and looks like there is nothing to shave.

Screenshot from 2021-08-01 21-09-09

**Comment by RDKRACZ** [comment]
Or it is?
`2.08% decrease`

Seems like a few files can be optimized a little more, looks like I will change the tool next time.

**Comment by wafflecoffee** [comment]
Yeah, I ran with `-o max` off of your branch and got 143 files changed

**Comment by RDKRACZ** [comment]
Want me to commit with `oxipng -o max` or are you gonna do it?

**Comment by wafflecoffee** [comment]
Oops, accidentally pushed to the actual C+ repo instead of your branch

**Pull request merged**
