### PR TITLE
Russian Translations

### PR DESCRIPTION
**Pull request by MobButcher**
Greetings!

I've noticed that your mod wasn't translated to Russian, so I decided to take it upon myself to help you out with that. Also, I'd love to be a maintainer for Russian, so if you need it updated, feel free to contact me and I'll try to quickly help you out.

Thank you for the mod and I hope you will have much more content to come in the near future. :heart:

### CODE REVIEW

**Comment by Cart3r1234** [comment]
Awesome.  We'll look over this in a bit, but it should be good to go to be added.  Thanks for taking the time to do this!

**Comment by MobButcher** [comment]
My pleasure. I've double-checked to see that everything's fine. I tried to follow Mojang guidelines and consulted with the Crowdin consensus, but I did change some translations because of my personal choice. Namely, I decided to forgo the transliteration of the word Nether, changing it to Hell, since "nether <whatever>" sounds harsh, crude, and foreign in Russian.

Also, I plan on adding Ukrainian translation soon, since the process is hopefully not that complicated, as I have the base ready.

**Comment by Cart3r1234** [comment]
Great!  If you wish, there's a translator role in our discord, so if you have a discord account and want to join, we can give you the role there.  The link to the discord should be somewhere on the wiki (probably the faq), but if not I can add it.

**Review by wafflecoffee — APPROVED** [review]

**Comment by Siuolthepic** [comment]
Finally someone else uses Translation tracking.

**Review by Siuolthepic — APPROVED** [review]

**Pull request merged**
