### PR TITLE
Update tok.json

### PR DESCRIPTION
**Pull request by ParanormalChicken**
yeah

### CODE REVIEW

**Comment by Cart3r1234** [comment]
Looks good to me, noticed 2 things though -
1. You removed most of the nubert strings but kept the nubert tooltip error.  That one can also be removed
2. I accidentally left "cobbled concrete" strings in the English file while I was creating the set.  The 5 strings pertaining to those can also be removed, sorry about that.

**Comment by ParanormalChicken** [comment]
github is too confusing i can't figure out how to change it 😭

**Comment by Cart3r1234** [comment]
Its alright, having the extra strings doesn't cause any issues, they just don't apply to anything.

**Comment by ParanormalChicken** [comment]
i think i got it fixed now

**Pull request merged**
